[package]
name = "semtech-lorawan-parser"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[[bin]]
name = "parse_packet"
doc = false

[dependencies]
futures = "0.1"
tokio-core = "0.1"
nom = "2.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
