[package]
name = "semtech-lorawan-server"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
nom = "2.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
